# Generated by Django 4.0.1 on 2022-01-27 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=150)),
                ('brand_slug', models.SlugField(max_length=150, unique=True)),
                ('brand_image', models.ImageField(upload_to='Brands')),
                ('brand_status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-brand_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=150)),
                ('prod_slug', models.SlugField(max_length=150, unique=True)),
                ('prod_price', models.FloatField()),
                ('offer_price', models.FloatField(blank=True, null=True)),
                ('prod_img', models.ImageField(null=True, upload_to='products')),
                ('prod_tag', models.CharField(max_length=20, unique=True)),
                ('prod_details', models.TextField(default='coming soon')),
                ('brands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand')),
            ],
            options={
                'ordering': ['-prod_name'],
            },
        ),
    ]
