# Generated by Django 4.0.1 on 2022-01-28 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['brand_name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-Prod_created']},
        ),
        migrations.AddField(
            model_name='product',
            name='Prod_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='prod_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
